#!/usr/bin/env python3
from sys import argv
from parser import parser, get_degree, is_term, is_number

allowed_symbols = ['X', '+', '-', '=', '^', '*', '.']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['+', '-', '=']


def change_operation(sign):
    return '+' if sign == '-' else '-'


def solver():
    pass


def move_terms_to_left(equation):
    equation = equation.replace(' * ', '*').split(' ')
    print(equation)
    right_side = []
    left_side = []
    for i in equation[::-1]:
        if i == '=':
            break
        else:
            right_side.append(i)

    for i in equation:
        if i == '=':
            break
        else:
            left_side.append(i)
    right_side = right_side[::-1]
    tmp_right = [i for i in right_side]

    i = 0
    while i < len(right_side):
        if is_number(number=right_side[i]) or is_term(term=right_side[i]):
            # check if last item of left side is +/-.
            if left_side[-1] == '-' or left_side[-1] == '+':
                left_side.append(right_side[i])
            else:
                # check if previous item of equation is +/-.
                if equation[equation.index(right_side[i]) - 1] == '+' or equation[equation.index(right_side[i]) - 1] == '-':
                    left_side.append(change_operation(sign=equation[equation.index(right_side[i]) - 1]))
                else:
                    left_side.append('-')
                left_side.append(right_side[i])
        else:
            # in case if item is +/-
            left_side.append(change_operation(sign=right_side[i]))
            left_side.append(right_side[i + 1])
            i += 1
            tmp_right.pop(0)
        tmp_right.pop(0)
        print(left_side + ['='] + (tmp_right if tmp_right else ['0']))
        i += 1


# def get_reduced_form(equation: str) -> list:
#     equation = equation.replace(' * ', '*').split(' ')
#     print(equation)
#     right_side = []
#     for i in equation[::-1]:
#         if i == '=':
#             break
#         else:
#             right_side.append(i)
#     right_side = right_side[::-1]
#     print(right_side)
#     # right_side.
#     print(equation)


def main():
    if parser():
        equation = argv[1]
        get_degree(equation=equation)
        move_terms_to_left(equation=equation)
        # solver(equation=equation)
    else:
        print("Wrong input!")


if __name__ == "__main__":
    # print(change_operation(sign='-'))
    main()
