#!/usr/bin/env python3
from sys import argv

allowed_symbols = ['X', '+', '-', '=', '^', '*', '.']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['+', '-', '=']


def check_duplicates(source: str) -> bool:
    pass


def is_term(term: str) -> bool:
    if '*' in term and 'X' in term:
        number = term.split('*')
        try:
            float(number[0])
            # print(f"{number} is Term")
            return True
        except ValueError:
            # print(f'{number} Not a Term')
            return False
    elif term == 'X' or term == 'X^2':
        return True
    else:
        return False


def is_number(number: str) -> bool:
    try:
        float(number)
        # print(f"{number} is Number")
        return True
    except ValueError:
        # print(f'{number} NOT A NUMBER')
        return False


def check_lexicon(equation: str) -> bool:
    # TODO check that max pox not more than 2.
    if '=' in equation and any(i in equation for i in numbers) and any(i for i in allowed_symbols):
        if equation.replace(' ', ''):
            for i in equation.replace(' ', ''):
                if i not in allowed_symbols + numbers:
                    return False
            return True
    return False


def check_syntax(equation: str) -> bool:
    equation = equation.replace(' * ', '*')
    equation = equation.split(' ')
    print(equation)
    # if is_number(equation[0]) or equation[0] == 'X' or equation[0] == 'X^2':
    for i in range(len(equation)):
        if is_number(number=equation[i]) or is_term(term=equation[i]):
            print(f"number or term: {equation[i]}")
            # check if not last item
            if i != len(equation) - 1:
                if equation[i + 1] in symbols:
                    continue
            else:
                print("Last term reached!")
                return True
        elif equation[i] in symbols:
            # if not first or last symbol
            if i != 0 and i != len(equation) - 1:
                print(f"symbol: {equation[i]} {i}")
                # if item is -, +, = check next or previous symbol should be a term.
                if is_number(equation[i - 1]) or is_term(term=equation[i - 1]) or is_number(number=equation[i + 1]) or is_term(term=equation[i + 1]):
                    continue
                else:
                    print("Wrong position of sign")
                    return False
            else:
                print("Don't put sign at start or finish of equation.")
                return False
        else:
            print(f"Some shit in the input {equation[i]}")
            return False


def parser():
    if len(argv) == 1:
        print("You didn't put any parameter!")
    elif len(argv) > 2:
        print("Too many parameters!")
    else:
        terms = {}
        equation = argv[1]
        if check_lexicon(equation=equation):
            print("Lexicon is ok!")
        if check_syntax(equation=equation):
            print("Syntax is ok!")
        else:
            print("Wrong input!")


def main():
    pass


if __name__ == "__main__":
    parser()
